spring:
  datasource:
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:C:\Users\BS-308\data\mlab
#    username: ${DB_USERNAME:sa}
#    password: ${DB_PASSWORD:password}

    url: ${DB_URL:jdbc:mysql://localhost:3306/mlab_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:toor}

#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  h2:
    console:
      enabled: true
      settings:
        trace: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true